// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsVDRokdIQAHMr74_5E-nC69a7Gdxd_6w',
    appId: '1:286685624859:web:f7e95229c5341adef4d6be',
    messagingSenderId: '286685624859',
    projectId: 'flexi-contractor',
    authDomain: 'flexi-contractor.firebaseapp.com',
    storageBucket: 'flexi-contractor.appspot.com',
    measurementId: 'G-9NC0YPM37Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXA42oIOrvP1I1__PK4ThhutqbPfMKEDw',
    appId: '1:286685624859:android:5c6e050b424b9fcdf4d6be',
    messagingSenderId: '286685624859',
    projectId: 'flexi-contractor',
    storageBucket: 'flexi-contractor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiYQ3YpYzk6HVuNmvkKKpKMPbdayW7T3E',
    appId: '1:286685624859:ios:e48b5c1e46992364f4d6be',
    messagingSenderId: '286685624859',
    projectId: 'flexi-contractor',
    storageBucket: 'flexi-contractor.appspot.com',
    iosClientId: '286685624859-1tf5fhpo1nirvullmo7m6sbgkb1uqu0e.apps.googleusercontent.com',
    iosBundleId: 'com.sprs.shop.flexiContractor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiYQ3YpYzk6HVuNmvkKKpKMPbdayW7T3E',
    appId: '1:286685624859:ios:e48b5c1e46992364f4d6be',
    messagingSenderId: '286685624859',
    projectId: 'flexi-contractor',
    storageBucket: 'flexi-contractor.appspot.com',
    iosClientId: '286685624859-1tf5fhpo1nirvullmo7m6sbgkb1uqu0e.apps.googleusercontent.com',
    iosBundleId: 'com.sprs.shop.flexiContractor',
  );
}
